##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

# Header
menu:
  - page: home
    directory: home/
    icon: fa-home
  - page: 文章列表
    directory: .
    icon: fa-fei
  - page: 文章归档
    directory: archives/
    icon: fa-archive
  - page: 作品展示
    directory: project/
    icon: fa-empty
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss


# Sidebar
# 微博秀地址设置 http://app.weibo.com/tool/weiboshow
widgets:
  - recent_posts
  - category
  - weibo
  - tag
  - archive
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  ## 友言(uid)
  uyan: 2130339
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)

#Share
baidu_share: true ## 百度分享
JiaThis_share: ##true ##JiaThis分享
duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

# About page
about:
  photo_url: /img/avatar.jpg ## Your photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  items:
  - label: email
    url: mailto:245803627@qq.com
    title: 245803627@qq.com
  - label: github
    url: https://github.com/seanpx
    title: sean's github
  - label: weibo
    url: http://weibo.com/317177730
    title:  闻言知意
  - label: csdn
    url: http://blog.csdn.net/arvin0
    title: sean's csdn blog
  - label: cnblog
    url: http://www.cnblogs.com/arvin0
    title:  sean's cnblog
# - label: twitter
#   url: 
#   title:
# - label: facebook
#   url:
#   title:

# Links widget. Empty links will hide widget.
links:
  # - title: site-name1
  #   url: http://www.example1.com/
  # - title: site-name2
  #   url: http://www.example2.com/
  # - title: site-name3
  #   url: http://www.example3.com/
